# Generated by Django 3.2.8 on 2022-01-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_berita', models.CharField(max_length=200)),
                ('headline', models.CharField(max_length=200)),
                ('thumbnail', models.CharField(max_length=200)),
                ('isi', models.CharField(max_length=200)),
                ('penulis', models.CharField(max_length=200)),
                ('tanggal_upload', models.CharField(max_length=200)),
            ],
        ),
    ]
